trigger:
- main

stages:

- stage: Docker
  dependsOn: []
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
  displayName: 'Docker Stage'
  jobs:
  - job: Build_Push_Docker_Image
    displayName: 'Build and Push Docker Image'
    pool:
      name: 'Default'
    steps:
    - task: Docker@2
      displayName: 'Build Docker Image'
      inputs:
        command: 'build'
        repository: 'azuredevops-431108/dockerregistry/microservice'
        dockerfile: Dockerfile
        containerRegistry: 'gcr'
        arguments: '--no-cache'
        tags: |
          latest
    - task: Docker@2
      displayName: 'Push Docker Image'
      inputs:
        command: 'push'
        repository: 'azuredevops-431108/dockerregistry/microservice'
        containerRegistry: 'gcr'
        tags: |
          latest
