apiVersion: v1
kind: Service
metadata:
  name: microservice
  namespace: microservice
  labels:
    app: microservice
spec:
  type: LoadBalancer
  selector:
    app: microservice
  ports:
    - name: http
      port: 80
      targetPort: 5000
